services:
  app:
    build:
      context: .
        dockerfile: Dockerfile
      volumes:
        - .:/app
        - node_modules:/app/node_modules
      ports:
        - 5173:5173
      command: npm run dev -- --host

volumes:
  node_modules:
